# Generated by Django 3.1.1 on 2020-09-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippingorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingorder',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Orderitems',
        ),
        migrations.DeleteModel(
            name='products',
        ),
        migrations.DeleteModel(
            name='ShippingOrder',
        ),
    ]
